[ERROR] (tests/ex29_tests.c:24: errno: None) Function fail_on_purpose return 1 for data: i fail,length:6
